//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TOUR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_SACH_DICH_VU
    {
        public int MA_DICH_VU { get; set; }
        public int MA_TOUR { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
    
        public virtual DICH_VU DICH_VU { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
