//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TOUR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICH_VU
    {
        public DICH_VU()
        {
            this.DANH_SACH_DICH_VU = new HashSet<DANH_SACH_DICH_VU>();
        }
    
        public int MA_DICH_VU { get; set; }
        public string TEN_DICH_VU { get; set; }
        public Nullable<double> GIA { get; set; }
    
        public virtual ICollection<DANH_SACH_DICH_VU> DANH_SACH_DICH_VU { get; set; }
    }
}
