//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TOUR
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_TOUR
    {
        public LOAI_TOUR()
        {
            this.TOURs = new HashSet<TOUR>();
        }
    
        public int MA_LOAI { get; set; }
        public string TEN_LOAI { get; set; }
    
        public virtual ICollection<TOUR> TOURs { get; set; }
    }
}
