//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TOUR
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINH
    {
        public TINH()
        {
            this.DIA_DIEM_DU_LICH = new HashSet<DIA_DIEM_DU_LICH>();
            this.KHACH_SAN = new HashSet<KHACH_SAN>();
        }
    
        public int MA_TINH { get; set; }
        public string TEN_TINH { get; set; }
    
        public virtual ICollection<DIA_DIEM_DU_LICH> DIA_DIEM_DU_LICH { get; set; }
        public virtual ICollection<KHACH_SAN> KHACH_SAN { get; set; }
    }
}
