//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_THAM_QUAN
    {
        public int MA_DIA_DIEM { get; set; }
        public int MA_TOUR { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual DIA_DIEM_DU_LICH DIA_DIEM_DU_LICH { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
