//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUONG_TRINH_TOUR
    {
        public int MA_CHUONG_TRINH { get; set; }
        public Nullable<int> MA_KHACH_SAN { get; set; }
        public Nullable<int> MA_TOUR { get; set; }
        public string TEN_CHUONG_TRINH { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string CHI_TIET { get; set; }
    
        public virtual TOUR TOUR { get; set; }
        public virtual KHACH_SAN KHACH_SAN { get; set; }
    }
}
