//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_KHOI_HANH
    {
        public LICH_KHOI_HANH()
        {
            this.TOUR_DAT = new HashSet<TOUR_DAT>();
        }
    
        public int MA_LICH { get; set; }
        public Nullable<int> MA_TOUR { get; set; }
        public string TEN_LICH { get; set; }
        public Nullable<System.DateTime> NGAY_KHOI_HANH { get; set; }
    
        public virtual TOUR TOUR { get; set; }
        public virtual ICollection<TOUR_DAT> TOUR_DAT { get; set; }
    }
}
