//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_THANH_TOAN
    {
        public LOAI_THANH_TOAN()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public int MA_LOAI_TT { get; set; }
        public string TEN_LOAI_TT { get; set; }
        public string CHI_TIET { get; set; }
    
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
    }
}
