//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_TOUREntities : DbContext
    {
        public DB_TOUREntities()
            : base("name=DB_TOUREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHI_TIET_THAM_QUAN> CHI_TIET_THAM_QUAN { get; set; }
        public DbSet<CHUONG_TRINH_TOUR> CHUONG_TRINH_TOUR { get; set; }
        public DbSet<DANH_SACH_DICH_VU> DANH_SACH_DICH_VU { get; set; }
        public DbSet<DIA_DIEM_DU_LICH> DIA_DIEM_DU_LICH { get; set; }
        public DbSet<DICH_VU> DICH_VU { get; set; }
        public DbSet<HOA_DON> HOA_DON { get; set; }
        public DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public DbSet<KHACH_SAN> KHACH_SAN { get; set; }
        public DbSet<LICH_KHOI_HANH> LICH_KHOI_HANH { get; set; }
        public DbSet<LOAI_THANH_TOAN> LOAI_THANH_TOAN { get; set; }
        public DbSet<LOAI_TOUR> LOAI_TOUR { get; set; }
        public DbSet<TINH> TINHs { get; set; }
        public DbSet<TOUR> TOURs { get; set; }
        public DbSet<TOUR_DAT> TOUR_DAT { get; set; }
        public DbSet<MAN_HINH> MAN_HINH { get; set; }
        public DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public DbSet<NHAN_VIEN_NHOM> NHAN_VIEN_NHOM { get; set; }
        public DbSet<NHOM> NHOMs { get; set; }
        public DbSet<PHAN_QUYEN> PHAN_QUYEN { get; set; }
    }
}
